local g = require("scripts.global")

local button

function init(self)
    msg.post(".", "acquire_input_focus")
    button = gui.get_node("start_btn")

end

function on_input(self, action_id, action)
    if action_id == hash("mouse_click") and action.pressed then -- <2>
        if gui.pick_node(button, action.x, action.y) then -- <5>
            msg.post(g.proxy_url, "game")
        end
    end
end
