local ship = require("scripts.spaceship")

local g = require("scripts.global")

function init(self)
    msg.post(".", "acquire_input_focus")

    g.init()
    ship.init()

end

function final(self)
   
   -- aabb.clear()
end

function update(self, dt)
    ship.update(dt)

end


function on_input(self, action_id, action)
    ship.input(action_id, action)

    if action_id == hash("toggle_debug") and action.pressed then
        msg.post("@system:", "toggle_profile")
    end
end

