local g = require("scripts.global")
go.property("aabb_id", -1)

function init(self)
    self.aabb_id = aabb.insert_gameobject(g.enemy_group_id, msg.url("."), 5, 5)
    local v = {
        url = msg.url("."), 
        aabb_id = self.aabb_id, 
        active = true
    }

    g.missiles[self.aabb_id] = v

end

function final(self)

    g.missiles[self.aabb_id] = nil
    aabb.remove_gameobject(g.enemy_group_id, self.aabb_id)
end
